/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as deleteVerifierSol from "./deleteVerifier.sol";
export * as insertVerifierSol from "./insertVerifier.sol";
export * as selectVerifierSol from "./selectVerifier.sol";
export * as updateVerifierSol from "./updateVerifier.sol";
export * as zkSqlSol from "./zkSQL.sol";
