build:
	bash scripts/compile-circuit.sh select
	bash scripts/compile-circuit.sh insert
	bash scripts/compile-circuit.sh update
	bash scripts/compile-circuit.sh delete
	npx hardhat compile
	npx hardhat typechain
