/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInsertVerifier,
  IInsertVerifierInterface,
} from "../../zkSQL.sol/IInsertVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "uint256[]",
        name: "pubSignals",
        type: "uint256[]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IInsertVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IInsertVerifierInterface {
    return new utils.Interface(_abi) as IInsertVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInsertVerifier {
    return new Contract(address, _abi, signerOrProvider) as IInsertVerifier;
  }
}
